// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apm.proto

package apm

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_963ff4f69d01b4f1, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type GetResponse struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_963ff4f69d01b4f1, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

type GetDelayRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDelayRequest) Reset()         { *m = GetDelayRequest{} }
func (m *GetDelayRequest) String() string { return proto.CompactTextString(m) }
func (*GetDelayRequest) ProtoMessage()    {}
func (*GetDelayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_963ff4f69d01b4f1, []int{2}
}

func (m *GetDelayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDelayRequest.Unmarshal(m, b)
}
func (m *GetDelayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDelayRequest.Marshal(b, m, deterministic)
}
func (m *GetDelayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDelayRequest.Merge(m, src)
}
func (m *GetDelayRequest) XXX_Size() int {
	return xxx_messageInfo_GetDelayRequest.Size(m)
}
func (m *GetDelayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDelayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDelayRequest proto.InternalMessageInfo

type GetDelayResponse struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDelayResponse) Reset()         { *m = GetDelayResponse{} }
func (m *GetDelayResponse) String() string { return proto.CompactTextString(m) }
func (*GetDelayResponse) ProtoMessage()    {}
func (*GetDelayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_963ff4f69d01b4f1, []int{3}
}

func (m *GetDelayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDelayResponse.Unmarshal(m, b)
}
func (m *GetDelayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDelayResponse.Marshal(b, m, deterministic)
}
func (m *GetDelayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDelayResponse.Merge(m, src)
}
func (m *GetDelayResponse) XXX_Size() int {
	return xxx_messageInfo_GetDelayResponse.Size(m)
}
func (m *GetDelayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDelayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDelayResponse proto.InternalMessageInfo

func (m *GetDelayResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "charlotte.test.apm.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "charlotte.test.apm.GetResponse")
	proto.RegisterType((*GetDelayRequest)(nil), "charlotte.test.apm.GetDelayRequest")
	proto.RegisterType((*GetDelayResponse)(nil), "charlotte.test.apm.GetDelayResponse")
}

func init() { proto.RegisterFile("apm.proto", fileDescriptor_963ff4f69d01b4f1) }

var fileDescriptor_963ff4f69d01b4f1 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4a, 0xce, 0x48, 0x2c, 0xca, 0xc9, 0x2f, 0x29, 0x49,
	0xd5, 0x2b, 0x49, 0x2d, 0x2e, 0xd1, 0x4b, 0x2c, 0xc8, 0x55, 0xe2, 0xe1, 0xe2, 0x72, 0x4f, 0x2d,
	0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x52, 0xe6, 0xe2, 0x06, 0xf3, 0x8a, 0x0b, 0xf2,
	0xf3, 0x8a, 0x53, 0x85, 0x44, 0xb8, 0x58, 0x8b, 0x52, 0x0b, 0x72, 0x2a, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0x20, 0x1c, 0x25, 0x41, 0x2e, 0x7e, 0xf7, 0xd4, 0x12, 0x97, 0xd4, 0x9c, 0xc4,
	0x4a, 0x98, 0x3e, 0x0d, 0x2e, 0x01, 0x84, 0x10, 0x3e, 0xcd, 0x46, 0xab, 0x19, 0xb9, 0xb8, 0x1c,
	0x0b, 0x72, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0xdc, 0xb8, 0x98, 0xdd, 0x53, 0x4b,
	0x84, 0xe4, 0xf4, 0x30, 0x9d, 0xa6, 0x87, 0x70, 0x97, 0x94, 0x3c, 0x4e, 0x79, 0xa8, 0x65, 0xa1,
	0x5c, 0x1c, 0x30, 0x07, 0x08, 0x29, 0xe3, 0x50, 0x8c, 0xec, 0x62, 0x29, 0x15, 0xfc, 0x8a, 0x20,
	0xc6, 0x3a, 0x49, 0x45, 0x31, 0x27, 0x16, 0xe4, 0x9e, 0x62, 0x12, 0x72, 0x86, 0x29, 0x8e, 0x09,
	0x49, 0x2d, 0x2e, 0x89, 0x71, 0x2c, 0xc8, 0x4d, 0x62, 0x03, 0x07, 0xaa, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0xb7, 0x3a, 0xc3, 0x0b, 0x61, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApmServiceClient is the client API for ApmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApmServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetDelay(ctx context.Context, in *GetDelayRequest, opts ...grpc.CallOption) (*GetDelayResponse, error)
}

type apmServiceClient struct {
	cc *grpc.ClientConn
}

func NewApmServiceClient(cc *grpc.ClientConn) ApmServiceClient {
	return &apmServiceClient{cc}
}

func (c *apmServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/charlotte.test.apm.ApmService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apmServiceClient) GetDelay(ctx context.Context, in *GetDelayRequest, opts ...grpc.CallOption) (*GetDelayResponse, error) {
	out := new(GetDelayResponse)
	err := c.cc.Invoke(ctx, "/charlotte.test.apm.ApmService/GetDelay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApmServiceServer is the server API for ApmService service.
type ApmServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetDelay(context.Context, *GetDelayRequest) (*GetDelayResponse, error)
}

func RegisterApmServiceServer(s *grpc.Server, srv ApmServiceServer) {
	s.RegisterService(&_ApmService_serviceDesc, srv)
}

func _ApmService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApmServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charlotte.test.apm.ApmService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApmServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApmService_GetDelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApmServiceServer).GetDelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charlotte.test.apm.ApmService/GetDelay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApmServiceServer).GetDelay(ctx, req.(*GetDelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApmService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "charlotte.test.apm.ApmService",
	HandlerType: (*ApmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ApmService_Get_Handler,
		},
		{
			MethodName: "GetDelay",
			Handler:    _ApmService_GetDelay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apm.proto",
}
